/* Auto-generated by tools/gen_gbk_table.py - do not edit. */
#ifndef GBK_TABLE_H
#define GBK_TABLE_H

#include <stdint.h>

/* GBK(CP936) value for each BMP Unicode code point; 0xFFFF = unmapped. */
extern const uint16_t gbk_bmp_table[0x10000];

static inline uint16_t gbk_from_unicode(uint32_t cp) {
    if (cp >= 0x10000u) return 0xFFFFu;
    return gbk_bmp_table[cp];
}

#endif /* GBK_TABLE_H */
