# -*- coding: utf-8 -*-
"""Generate a BMP -> GBK(CP936) mapping table for the Pico HID firmware.

Windows "Alt + Numpad decimal" entry on a Chinese-locale Windows maps the
typed decimal number to the ANSI/OEM code page (CP936/GBK).  For two-byte GBK
characters the decimal value is (lead_byte << 8) | trail_byte, e.g.
U+4E2D 中 = GBK D6D0 = 54992.  This lets HID-only keyboards (no software on the
target PC) type Chinese into non-RichEdit apps (browsers, chat apps, ...).

Usage: python tools/gen_gbk_table.py <out.c> <out.h>
"""
import sys

def main():
    out_c = sys.argv[1] if len(sys.argv) > 1 else "gbk_table.c"
    out_h = sys.argv[2] if len(sys.argv) > 2 else "gbk_table.h"

    table = [0xFFFF] * 0x10000
    for cp in range(0x10000):
        try:
            b = chr(cp).encode("gbk")
            if len(b) == 2:
                table[cp] = (b[0] << 8) | b[1]
            elif len(b) == 1:
                table[cp] = b[0]
        except UnicodeEncodeError:
            pass

    with open(out_c, "w", encoding="utf-8", newline="\n") as f:
        f.write("/* Auto-generated by tools/gen_gbk_table.py - do not edit. */\n")
        f.write('#include "gbk_table.h"\n\n')
        f.write("const uint16_t gbk_bmp_table[0x10000] = {\n")
        for i in range(0, 0x10000, 16):
            row = ", ".join("0x%04X" % table[j] for j in range(i, i + 16))
            f.write("    " + row + ",\n")
        f.write("};\n")

    with open(out_h, "w", encoding="utf-8", newline="\n") as f:
        f.write("/* Auto-generated by tools/gen_gbk_table.py - do not edit. */\n")
        f.write("#ifndef GBK_TABLE_H\n#define GBK_TABLE_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("/* GBK(CP936) value for each BMP Unicode code point; 0xFFFF = unmapped. */\n")
        f.write("extern const uint16_t gbk_bmp_table[0x10000];\n\n")
        f.write("static inline uint16_t gbk_from_unicode(uint32_t cp) {\n")
        f.write("    if (cp >= 0x10000u) return 0xFFFFu;\n")
        f.write("    return gbk_bmp_table[cp];\n")
        f.write("}\n\n")
        f.write("#endif /* GBK_TABLE_H */\n")

    mapped = sum(1 for v in table if v != 0xFFFF)
    print("wrote %s and %s (mapped %d BMP code points)" % (out_c, out_h, mapped))

if __name__ == "__main__":
    main()
